server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: ivannasekin
    password: hexlet!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
